1. Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.
Создать 5 двумерных массивов разной формы из массива a. 
Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).


In [4]:
import numpy as np

In [5]:
a = np.array([i for i in range (12,24)],dtype = int)

In [6]:
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [7]:
a1=np.reshape(a, (2, 6))
a2=np.reshape(a, (3, 4))
a3=np.reshape(a, (4, 3))
a4=np.reshape(a, (6, 2))
a5=np.reshape(a, (12, 1))


In [8]:
a1,a2,a3,a4,a5

(array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]), array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]), array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]), array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]), array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

In [9]:
a6=np.reshape(a, (2, -1))
a7=np.reshape(a, (3, -1))
a8=np.reshape(a, (4, -1))
a9=np.reshape(a, (-1, 2))
a10=np.reshape(a, (-1, 1))

In [10]:
a6,a7,a8,a9,a10

(array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]), array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]), array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]), array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]), array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным? - Нет. Нельзя. Одномерный массив, это массив из одной строки, а массив-столбец, это уже 12 строк. ИМХО. 


2. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения  со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. 
Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [11]:
b = np.reshape((np.random.standard_normal(size=(12, 1, 1))), (3, 4))

In [12]:
b

array([[ 2.27357785, -0.21514657,  0.42838788, -1.55406248],
       [ 1.6211796 ,  0.33024594,  1.48067421, -0.66005675],
       [-0.21074491, -0.73808317, -1.83911152, -0.86585944]])

In [13]:
b1 = np.reshape(b, (1, 12))

In [14]:
b1

array([[ 2.27357785, -0.21514657,  0.42838788, -1.55406248,  1.6211796 ,
         0.33024594,  1.48067421, -0.66005675, -0.21074491, -0.73808317,
        -1.83911152, -0.86585944]])

In [15]:
b.size==b1.size

True

3. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2. 
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. 
В чем разница между массивами a и b?


In [16]:
a = np.array([i for i in range (20,0,-2)],dtype = int)

In [17]:
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [18]:
b = np.reshape((np.array([i for i in range (20,1,-2)],dtype = int)),(1,10))

In [19]:
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [20]:
a==b

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

Как показало поэлеметное сравнение разницы нет. т.к. шаг четный и в обоих случаях конечный элемент массива, это 2

4. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.


In [21]:
a = np.zeros ((2, 2))

In [22]:
a

array([[0., 0.],
       [0., 0.]])

In [23]:
b = np.ones ((3, 2))

In [24]:
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
v = np.vstack((a,b))

In [26]:
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
v.size==10

True

5. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов.
Получить матрицу At путем транспонирования матрицы A.
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [28]:
a = np.array([i for i in range (0,12)],dtype = int)

In [29]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
A = np.reshape(a,(4,3))

In [31]:
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
At = A.transpose ()

In [33]:
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [34]:
B= np.dot(A,At)

In [35]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [36]:
print ("Размер матрицы В = ", B.shape)

Размер матрицы В =  (4, 4)


In [37]:
if len (B)==len(B[0]):
    if np.linalg.det(B)==0:
        print ('Обратной матрицы у квадратной матрицы В не существует, т.к. ее определитель = 0 и она вырожденная')
    else:
        print ('Обратная матрица для квадратной матрицы В = \n', np.linalg.inv(B))
else:
    print ('Обратной матрицы у матрицы В не существует, т.к. она не квадратная')

Обратной матрицы у квадратной матрицы В не существует, т.к. ее определитель = 0 и она вырожденная


6. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 
Поменяйте его форму так, чтобы получилась квадратная матрица C. 
Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [38]:
np.random.seed(42)

In [39]:
c = np.random.randint(0,16,16)

In [40]:
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [41]:
C=np.reshape(c,(4,4))

In [42]:
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [43]:
D = 10*C+B

In [58]:
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [59]:
print ('Определитель матрицы D =', np.linalg.det(D))

Определитель матрицы D = -28511999.999999944


In [60]:
print ('Ранг матрицы D =', np.linalg.matrix_rank(D))

Ранг матрицы D = 4


In [61]:
if len (D)==len(D[0]):
    if np.linalg.det(D)==0:
        print ('Обратной матрицы у квадратной матрицы D не существует, т.к. ее определитель = 0 и она вырожденная')
    else:
        Dinv = np.linalg.inv(D)
        print ('Обратная матрица для квадратной матрицы D = \n', Dinv)
else:
    print ('Обратной матрицы у матрицы D не существует, т.к. она не квадратная')

Обратная матрица для квадратной матрицы D = 
 [[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


7. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. 
С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4. 
Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [64]:
Dinv = np.where(Dinv > 0, 1 , Dinv)
Dinv = np.where(Dinv < 0, 0 , Dinv)
Dinv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [65]:
if (np.logical_or(Dinv == 0, Dinv == 1)).all()==True:
    print ('В массиве Dinv все значения равны 0 или 1')
else:
    print ('В массиве Dinv не все значения равны 0 или 1')


В массиве Dinv все значения равны 0 или 1
