1. Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.
Создать 5 двумерных массивов разной формы из массива a. 
Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).


In [1]:
import numpy as np

In [2]:
a = np.array([i for i in range (12,24)],dtype = int)

In [3]:
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [4]:
a1=np.reshape(a, (2, 6))
a2=np.reshape(a, (3, 4))
a3=np.reshape(a, (4, 3))
a4=np.reshape(a, (6, 2))
a5=np.reshape(a, (12, 1))


In [5]:
a1,a2,a3,a4,a5

(array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]), array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]), array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]), array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]), array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

In [6]:
a6=np.reshape(a, (2, -1))
a7=np.reshape(a, (3, -1))
a8=np.reshape(a, (4, -1))
a9=np.reshape(a, (-1, 2))
a10=np.reshape(a, (-1, 1))

In [7]:
a6,a7,a8,a9,a10

(array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]), array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]), array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]), array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]), array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным? - Нет. Нельзя. Одномерный массив, это массив из одной строки, а массив-столбец, это уже 12 строк. ИМХО. 


2. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения  со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. 
Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [8]:
b = np.reshape((np.random.standard_normal(size=(12, 1, 1))), (3, 4))

In [9]:
b

array([[ 0.01089132, -0.37512753, -1.55971972,  2.41903011],
       [ 0.19393818,  0.51209878, -1.12956559,  0.04469805],
       [ 0.27365136,  1.10191483,  0.06206842,  0.83663542]])

In [10]:
b1 = np.reshape(b, (1, 12))

In [11]:
b1

array([[ 0.01089132, -0.37512753, -1.55971972,  2.41903011,  0.19393818,
         0.51209878, -1.12956559,  0.04469805,  0.27365136,  1.10191483,
         0.06206842,  0.83663542]])

In [12]:
b.size==b1.size

True

3. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2. 
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. 
В чем разница между массивами a и b?


In [13]:
a = np.array([i for i in range (20,0,-2)],dtype = int)

In [14]:
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [15]:
b = np.reshape((np.array([i for i in range (20,1,-2)],dtype = int)),(1,10))

In [16]:
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [17]:
a==b

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

Как показало поэлеметное сравнение разницы нет. т.к. шаг четный и в обоих случаях конечный элемент массива, это 2

4. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.


In [18]:
a = np.zeros ((2, 2))

In [19]:
a

array([[0., 0.],
       [0., 0.]])

In [20]:
b = np.ones ((3, 2))

In [21]:
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [22]:
v = np.vstack((a,b))

In [23]:
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
v.size==10

True

5. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов.
Получить матрицу At путем транспонирования матрицы A.
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [25]:
a = np.array([i for i in range (0,12)],dtype = int)

In [26]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
A = np.reshape(a,(4,3))

In [28]:
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
At = A.transpose ()

In [30]:
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [31]:
B= np.dot(A,At)

In [32]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [33]:
print ("Размер матрицы В = ", B.shape)

Размер матрицы В =  (4, 4)


In [34]:
if len (B)==len(B[0]):
    if np.linalg.det(B)==0:
        print ('Обратной матрицы у квадратной матрицы В не существует, т.к. ее определитель = 0 и она вырожденная')
    else:
        print ('Обратная матрица для квадратной матрицы В = \n', np.linalg.inv(B))
else:
    print ('Обратной матрицы у матрицы В не существует, т.к. она не квадратная')

Обратной матрицы у квадратной матрицы В не существует, т.к. ее определитель = 0 и она вырожденная


6. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 
Поменяйте его форму так, чтобы получилась квадратная матрица C. 
Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [35]:
np.random.seed(42)

In [36]:
c = np.random.randint(0,16,16)

In [37]:
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [38]:
C=np.reshape(c,(4,4))

In [39]:
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [40]:
D = 10*C+B

In [41]:
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [42]:
print ('Определитель матрицы D =', np.linalg.det(D))

Определитель матрицы D = -28511999.999999944


In [43]:
print ('Ранг матрицы D =', np.linalg.matrix_rank(D))

Ранг матрицы D = 4


In [44]:
if len (D)==len(D[0]):
    if np.linalg.det(D)==0:
        print ('Обратной матрицы у квадратной матрицы D не существует, т.к. ее определитель = 0 и она вырожденная')
    else:
        Dinv = np.linalg.inv(D)
        print ('Обратная матрица для квадратной матрицы D = \n', Dinv)
else:
    print ('Обратной матрицы у матрицы D не существует, т.к. она не квадратная')

Обратная матрица для квадратной матрицы D = 
 [[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


7. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. 
С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4. 
Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [47]:
Dinv = np.where(Dinv > 0, 1 , 0)
#Dinv = np.where(Dinv < 0, 0 , Dinv)
Dinv

array([[1, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 1, 0]])

In [46]:
if (np.logical_or(Dinv == 0, Dinv == 1)).all()==True:
    print ('В массиве Dinv все значения равны 0 или 1')
else:
    print ('В массиве Dinv не все значения равны 0 или 1')


В массиве Dinv все значения равны 0 или 1


In [48]:
E = np.where(Dinv, B, C)

In [49]:
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])

Задание 2
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.
Будем считать, что каждый столбец - это признак, а строка - наблюдение.
Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy.
Результат запишите в массив mean_a, в нем должно быть 2 элемента.


In [53]:
a = np.reshape(np.array([1,6,2,8,3,11,3,10,1,7]),(5,2))
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [60]:
mean_a = np.mean(a, axis=0)
mean_a

array([2. , 8.4])

Задание 3
Вычислите массив a_centered, отняв от значений массива а средние значения соответствующих признаков, содержащиеся в массиве mean_a.
Вычисление должно производиться в одно действие.
Получившийся массив должен иметь размер 5x2.


In [61]:
a_centered = a-mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 4
Найдите скалярное произведение столбцов массива a_centered.
В результате должна получиться величина a_centered_sp. 
Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [66]:
a_centered_sp = np.dot(a_centered[:,0],a_centered[:,1])
kov1_a = a_centered_sp/(len(a_centered)-1)
a_centered_sp,kov1_a

(8.0, 2.0)

Задание 5**
Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве а. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. 
В качестве аргумента m функция np.cov должна принимать транспонированный массив a.
В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение 
ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.



In [68]:
kov2_a= np.cov(np.transpose(a))
kov2_a

array([[1. , 2. ],
       [2. , 4.3]])

In [69]:
if kov1_a == kov2_a[0,1]:
    print ('Значения ковариаций совпали!! УРА!!! NUMPY ОСВОЕН!!!')
else:
    print('Значения ковариаций не совпали :(')

Значения ковариаций совпали!! УРА!!! NUMPY ОСВОЕН!!!


Задание 1
Импортируйте библиотеку Pandas и дайте ей псевдоним pd.
Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные:
[1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price,в которых соответственно содержатся данные: 
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].


In [71]:
import pandas as pd

In [73]:
authors = pd.DataFrame({"author_id":np.array([1, 2, 3]), "author_name": np.array(['Тургенев', 'Чехов', 'Островский'])}, index=[1, 2, 3])
print(authors)

   author_id author_name
1          1    Тургенев
2          2       Чехов
3          3  Островский


In [74]:
book = pd.DataFrame({"author_id":np.array([1, 1, 1, 2, 2, 3, 3]), "book_title": np.array(['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники']), "price": np.array([450, 300, 350, 500, 450, 370, 290])}, index=[1, 2, 3,4,5,6,7])
print(book)

   author_id            book_title  price
1          1           Отцы и дети    450
2          1                 Рудин    300
3          1     Дворянское гнездо    350
4          2      Толстый и тонкий    500
5          2       Дама с собачкой    450
6          3                 Гроза    370
7          3  Таланты и поклонники    290


Задание 2
Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.



In [76]:
authors_price=authors.merge(book)
print (authors_price)

   author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290


Задание 3
Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.


In [80]:
top5=authors_price.nlargest(5,'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

Задание 4
Создайте датафрейм authors_stat на основе информации из authors_price.
В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price, в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.


In [124]:
authors_stat1 = authors_price.groupby('author_name').agg({'price':'min'})
authors_stat2 = authors_price.groupby('author_name').agg({'price':'max'})
authors_stat3 = authors_price.groupby('author_name').agg({'price':'mean'})
authors_stat = pd.merge(authors_stat1,authors_stat2, on = 'author_name', how = 'outer')
authors_stat = pd.merge(authors_stat,authors_stat3, on = 'author_name', how = 'outer')
authors_stat.reset_index(inplace=True)
authors_stat.rename(columns={'price_x':'min_price','price_y':'max_price','price':'mean_price'})

author_name  min_price  max_price  mean_price
0  Островский        290        370  330.000000
1    Тургенев        300        450  366.666667
2       Чехов        450        500  475.000000

* Задание 5
Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая.
В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].
Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.
Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке.Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая",а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями,при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl".Затем загрузите из этого файла датафрейм и назовите его book_info2.Удостоверьтесь, что датафреймы book_info и book_info2 идентичны


In [127]:
authors_price['cover']=['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [133]:
pd.pivot_table?

In [153]:
book_info = pd.pivot_table(authors_price, values=['price'], index=['author_name','cover'], aggfunc={'price': sum})

In [154]:
book_info

price
author_name cover         
Островский  мягкая     660
Тургенев    мягкая     650
            твердая    450
Чехов       твердая    950

In [155]:
 pd.to_pickle(book_info, 'book_info.pkl')

In [157]:
book_info2=pd.read_pickle('book_info.pkl')

In [158]:
book_info2

price
author_name cover         
Островский  мягкая     660
Тургенев    мягкая     650
            твердая    450
Чехов       твердая    950